### ISSUE TITLE
Extended Emoji Set

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB-Community/nodebb-plugin-emoji-extended#12]
Plugin doesn't provide anymore http://www.emoji-cheat-sheet.com/ ?

**Comment by frissdiegurke** [comment]
Those are within the `nodebb-plugin-emoji-apple` set.

**Comment by NicolasSiver** [comment]
Will be helpful for future reference, if you will add link at plugin's README ;)
https://github.com/NodeBB-Community/nodebb-plugin-emoji-apple

**Comment by rbeer** [comment]
It's there. oO
https://github.com/NodeBB-Community/nodebb-plugin-emoji-extended/issues/12#emoji-sets

Or do you mean the emoji-cheat-sheet address?

**Comment by rbeer** [comment]
@NicolasSiver
Nevermind, I just figured what you meant. It's updated. Thanks for bringing it up! :smiley:

@frissdiegurke 
Updated the `MODULES` object in -extended, too.

**Comment by frissdiegurke** [comment]
@rbeer
Sorry to disappoint you, but I need to ask you to revert those changes (or I'll need to do so). I worked hard to get all license troubles out of those repositories. Since the apple emoji don't have a valid license for me to re-publish those, I coded emoji-apple to only download those from a third party. And this is the reason I used duckduckgo as a proxy for the image. It's done by purpose. I've made it clear within NodeBB ACP that those files are not licensed freely and using them is on own risk.

Yes, the link may stay within the readme, but no images containing emoji made by apple
containing emoji made by apple (without suiting license) within the repository please.

**Comment by rbeer** [comment]
@frissdiegurke 
Aww, I knew it! I was thinking: *odd that he forgot about this*. So don't worry, no disappointment here. Quite the opposite; sorry for barging in like that. :pensive: 

NodeBB-Community/nodebb-plugin-emoji-extended@d546d34
NodeBB-Community/nodebb-plugin-emoji-apple@7196d71
