### ISSUE TITLE
Inactive buttons

### ISSUE THREAD

**Issue by nhlpl** [NodeBB-Community/nodebb-plugin-emoji-extended#4]
NodeBB 1.0.1 version, v1.x.x branch, MongoDB 3.2.3, fresh install
OpenShift Cloud
Emoji Extended 1.0.3+1197 (installed by default)

Installed `nodebb-plugin-emoji-one` via Admin.
```
19/3 11:18 [347289] - [32minfo[39m: [plugins] nodebb@1.0.1 /var/lib/openshift/56ed4c8b2d5271819200011c/app-root/runtime/repo
`-- nodebb-plugin-emoji-one@1.0.2  extraneous
```

All buttons in Installed Sets tab are disabled.

![one](https://cloud.githubusercontent.com/assets/11160550/13899474/5bc12e54-edef-11e5-8d68-590f88c27020.jpg)

**Comment by frissdiegurke** [comment]
The "Update Files" button seems to be active. This is the default behavior after fresh installation.

You need to download the emoji files first before activation/file removal. The files are not shipped within NPM.

The [un]install action is not yet implemented. Thus deactivated for now. You have to [un]install via the ACP/Plugins page for now.

**Comment by nhlpl** [comment]
Sure, but I have downloaded nodebb-plugin-emoji-one and it seems to be detected by your plug-in.

I have followed your instructions:
https://community.nodebb.org/topic/8110/emoji/6

Please close this issue if you can't reproduce it. It might be something wrong with uploads folder on the cloud hosting level.

**Comment by nhlpl** [comment]
Clicked on `Update files` and it works. Strange. 
Activated!

Thanks.

**Comment by alexschomb** [comment]
Just in case someone else is having the same issues as I had:

If you are upgrading from an older version of nodeBB (e.g. v0.9.x) and had Emoji Extended installed before you'll need to completely remove it and restart nodeBB. Afterwards you can install the newest version via ACP, activate it and do the same for your desired emoji set. Otherwise all buttons will be grayed out (update button as well) and in some cases you can't even reach the plugin settings.
